# Generated by Django 4.1.6 on 2023-02-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_ceated_post_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishManager',
        ),
    ]
