# Generated by Django 4.1.6 on 2023-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_publishmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
